using System.Text.Json;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging.Abstractions;
using WorkJournal.Web.Models;
using WorkJournal.Web.Services;
int checks=0;
void Check(bool yes,string message){if(!yes)throw new Exception(message);Console.WriteLine("PASS: "+message);checks++;}
var fixture=new FixtureRadar();var snapshot=await fixture.GetAsync(default);var q=snapshot.Quotes[0];var h=FixtureRadar.History(q.Date);
var a=MarketRadarScoreCalculator.Calculate(q,h,snapshot.Events);
Check(a.AverageVolume5==1000 && a.AverageVolume20==1000 && a.VolumeRatio20==3 && a.VolumeGrowth20==200,"Exclude today and calculate 5/20 means, ratios and growth");
Check(a.Parts.Select(x=>x.Maximum).SequenceEqual(new[]{20,20,20,15,10,15}),"Six exact user weights");
Check(a.Available==100 && a.Score is >=0 and <=100,"Complete score only when every component available");
Check(JsonSerializer.Serialize(a)==JsonSerializer.Serialize(MarketRadarScoreCalculator.Calculate(q,h,snapshot.Events)),"Deterministic score and reasons");
for(var i=-90;i<=100;i++){
 var result=MarketRadarScoreCalculator.Calculate(q with{Change=i},h,snapshot.Events);
 Check(result.Earned>=0 && result.Earned<=100,"Score bounds for change "+i);
}
var shortHistory=h with{Bars=h.Bars.TakeLast(4).ToArray()};
var shortResult=MarketRadarScoreCalculator.Calculate(q,shortHistory,[]);
Check(shortResult.AverageVolume5==null && shortResult.AverageVolume20==null && shortResult.Technical.MA20==null && shortResult.Technical.RSI14==null && shortResult.Technical.Signal==null,"Insufficient history does not invent indicators");
var zero=MarketRadarScoreCalculator.Calculate(q,h with{Bars=h.Bars.Select(x=>x with{Volume=0}).ToArray()},[]);
Check(zero.AverageVolume20==0 && zero.VolumeRatio20==null,"Zero mean has no ratio");
var future=MarketRadarScoreCalculator.Calculate(q,h with{Bars=h.Bars.Append(new(q.Date,1,1,1,1,999999)).Append(new(q.Date.AddDays(1),1,1,1,1,999999)).ToArray()},snapshot.Events);
Check(future.AverageVolume20==a.AverageVolume20 && future.Technical.MA20==a.Technical.MA20,"No today or future leakage into prior history");
var absent=MarketRadarScoreCalculator.Calculate(q,h with{Flows=[]},[]);
Check(absent.Score==null && absent.Available==70 && absent.Earned<=70,"Missing chips and events remain unknown, no score renormalization");
var etf=MarketRadarScoreCalculator.Calculate(q with{Stock=q.Stock with{IsEtf=true}},h,snapshot.Events);
Check(etf.Parts[4].Points==null && etf.Score==null,"ETF never uses company revenue score");
var falling=MarketRadarScoreCalculator.Calculate(q with{Change=-10},h,snapshot.Events);
Check(falling.Parts[1].Points<=5 && falling.RiskFlags.Contains("大幅下跌") && falling.RiskFlags.Any(x=>x.Contains("量價背離")),"Falling on abnormal volume is risk, not bullish volume points");
using var memory=new MemoryCache(new MemoryCacheOptions());
var service=new MarketRadarService(fixture,fixture,memory,NullLogger<MarketRadarService>.Instance);
var basic=await service.GetAsync("all",null,false,default);
Check(basic.Quotes.Length==4 && basic.TradeDate==FixtureRadar.Day && fixture.Calls==0,"Initial daily rankings need no per-stock API");
Check(basic.Events.Any(x=>x.StockId=="9999"),"Suspended-stock announcements remain visible without closing quotes");
Check(basic.Quotes.OrderByDescending(x=>x.ChangePercent).First().Stock.Symbol=="2330","Gainers order");
Check(basic.Quotes.OrderBy(x=>x.ChangePercent).First().Stock.Symbol=="006208","Losers order");
Check(basic.Quotes.OrderByDescending(x=>x.Volume).First().Stock.Symbol=="6488","Share-volume order");
var complete=await service.GetAsync("all",null,true,default);var calls=fixture.Calls;
await Task.WhenAll(service.GetAsync("all",null,true,default),service.GetAsync("all",null,true,default));
Check(fixture.Calls==calls && calls==4,"Warm and concurrent requests reuse candidate histories");
Check(complete.Analysis.OrderByDescending(x=>x.VolumeRatio20).First().Quote.Stock.Symbol=="6488","Abnormal volume order");
Check((await service.GetAsync("etf",null,false,default)).Quotes.Length==2 && (await service.GetAsync("tpex",null,false,default)).Quotes.Length==1,"ETF and OTC filters");
Check((await service.GetAsync("all",FixtureRadar.Day.AddDays(-1),false,default)).Quotes.Single().Stock.Symbol=="1234","Do not mix trading dates");
Check(MarketRadarService.Candidates(Enumerable.Range(2000,300).Select(i=>q with{Stock=q.Stock with{Symbol=i.ToString()},Change=i%30-15,Volume=i})).Length<=60,"Candidate analysis bounded at 60, unique symbols");
using var failedCache=new MemoryCache(new MemoryCacheOptions());fixture.FailOne=true;
var failed=await new MarketRadarService(fixture,fixture,failedCache,NullLogger<MarketRadarService>.Instance).GetAsync("all",null,true,default);
Check(failed.Analysis.Length==4 && failed.Analysis.Any(x=>x.AverageVolume20==null) && !JsonSerializer.Serialize(failed).Contains("SECRET"),"Single-symbol failure isolated and sanitized");
calls=fixture.Calls;await new MarketRadarService(fixture,fixture,failedCache,NullLogger<MarketRadarService>.Instance).GetAsync("all",null,true,default);
Check(fixture.Calls==calls,"Failures negative-cached");
using var cts=new CancellationTokenSource();cts.Cancel();
try{await service.GetAsync("all",null,true,cts.Token);Check(false,"Cancellation");}catch(OperationCanceledException){Check(true,"Cancellation honored");}
Check(TaiwanMarketRankingProvider.Date("1151005")==FixtureRadar.Day && TaiwanMarketRankingProvider.Number("1,234.50")==1234.5m,"Official ROC dates and share units");
var root=JsonDocument.Parse("""[{"Date":"1151005","SecuritiesCompanyCode":"2330","Close":"110","Change":"-10","TradingShares":"1,234"},{"Date":"bad","SecuritiesCompanyCode":"2330","Close":"110","Change":"0","TradingShares":"10"}]""");
var parsed=TaiwanMarketRankingProvider.ParseArray(root.RootElement,[q.Stock with{Market="tpex"}],"tpex");
Check(parsed.Length==1 && parsed[0].Volume==1234 && parsed[0].Change<0,"OTC parser, malformed-date skip and shares not lots");
var twseJson=JsonDocument.Parse("""{"date":"20261005","tables":[null,{"fields":{},"data":[]},{"fields":["證券代號","收盤價","成交股數","漲跌價差","漲跌(+/-)"],"data":[null,["2330","110","1,234","10","<p>-</p>"],["2330","110","2","10","X"]]}]}""");
var twseParsed=TaiwanMarketRankingProvider.ParseTwse(twseJson.RootElement,[q.Stock]);
Check(twseParsed.Length==2 && twseParsed[0].Change==-10 && twseParsed[1].Change==null,"TWSE sign markup, corporate-action unknowns and malformed rows");
var eventJson=JsonDocument.Parse("""[null,{"公司代號":"2330","發言日期":"1151005","發言時間":"90000","主旨 ":"法說公告","說明":"Test"}]""");
var parsedEvents=TaiwanMarketRankingProvider.ParseEvents(eventJson.RootElement,"TWSE");
Check(parsedEvents.Length==1 && parsedEvents[0].Category=="法說會" && parsedEvents[0].PublishedAt.Hour==9 && parsedEvents[0].Impact=="Unknown","Official event timestamp and non-speculative impact");
Console.WriteLine($"{checks} market radar checks passed.");
