// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkJournal.Web.Data;

#nullable disable

namespace WorkJournal.Web.Data.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20260922212853_AddPaperTrading")]
    partial class AddPaperTrading
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkJournal.Web.Models.PaperOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ClientRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly?>("EligibleFromTradeDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FilledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("FilledPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateOnly?>("FilledTradeDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsEtf")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("LastEvaluatedTradeDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("LimitPrice")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("OrderType")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("RejectReason")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly?>("SubmittedTradeDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ClientRequestId")
                        .IsUnique();

                    b.HasIndex("AccountId", "Status", "CreatedAt");

                    b.ToTable("PaperOrders", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperOrder_Enums", "[Side] IN (0,1) AND [OrderType] IN (0,1) AND [Status] IN (0,1,2,3)");

                            t.HasCheckConstraint("CK_PaperOrder_Limit", "([OrderType] = 0 AND [LimitPrice] IS NULL) OR ([OrderType] = 1 AND [LimitPrice] > 0)");

                            t.HasCheckConstraint("CK_PaperOrder_Quantity", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperPosition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("AverageCost")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("CostBasis")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("RealizedProfitLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "StockId")
                        .IsUnique();

                    b.ToTable("PaperPositions", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperPosition_Quantity", "[Quantity] >= 0 AND [CostBasis] >= 0 AND [AverageCost] >= 0");
                        });
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperTrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Commission")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExecutionSequence")
                        .HasColumnType("int");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<decimal>("NetCashAmount")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateOnly>("QuoteTradeDate")
                        .HasColumnType("date");

                    b.Property<decimal>("RealizedProfitLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<int>("Side")
                        .HasColumnType("int");

                    b.Property<string>("StockId")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("TransactionTax")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExecutedAt");

                    b.HasIndex("OrderId", "ExecutionSequence")
                        .IsUnique();

                    b.ToTable("PaperTrades", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperTrade_Amounts", "[Quantity] > 0 AND [Price] > 0 AND [Commission] >= 0 AND [TransactionTax] >= 0");
                        });
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperTradingAccount", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<decimal>("Cash")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("Generation")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("InitialCash")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("RealizedProfitLoss")
                        .HasPrecision(28, 10)
                        .HasColumnType("decimal(28,10)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("PaperTradingAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaperAccount_Cash", "[Cash] >= 0 AND [InitialCash] > 0");

                            t.HasCheckConstraint("CK_PaperAccount_Singleton", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("WorkJournal.Web.Models.WorkLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time");

                    b.Property<decimal>("Hours")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NextSteps")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Project")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkDate");

                    b.ToTable("WorkLogs");
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperOrder", b =>
                {
                    b.HasOne("WorkJournal.Web.Models.PaperTradingAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperPosition", b =>
                {
                    b.HasOne("WorkJournal.Web.Models.PaperTradingAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkJournal.Web.Models.PaperTrade", b =>
                {
                    b.HasOne("WorkJournal.Web.Models.PaperTradingAccount", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkJournal.Web.Models.PaperOrder", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
